# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Kritner's Blog
subtitle: Just tryin to learn some stuff and teach some stuff
description: Join me in programming/coding, cooking, and controlled rotting of food.  I'm a developer who's always trying to learn more; I hope that this blog helps reinforce my own knowledge, and help others in theirs!
keywords: programming, how-to, development, tutorial
author: Russ Hammett
language: en
timezone: America/New_York

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.kritner.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year:month:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: true
  hljs: true
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: icarus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# rss
feed:
  type: atom
  path: atom.xml
  limit: 0
  hub:
  content: true
  content_limit: 140
  content_limit_delim: '...'
  order_by: -date
  icon: icon.png

# sitemap
sitemap:
  path: sitemap.xml
  rel: false
  tags: true
  categories: true